import { Box } from '@mui/material';
import type { Meta, StoryObj } from '@storybook/react';

import { EventFormPanel } from '../components/EventFormPanel';

const meta: Meta<typeof EventFormPanel> = {
  title: 'Components/Forms/EventFormPanel',
  component: EventFormPanel,
  parameters: {
    layout: 'fullscreen',
    backgrounds: { default: 'light' },
  },
  decorators: [
    (Story) => (
      <Box sx={{ p: 4, maxWidth: 1000, mx: 'auto' }}>
        <Story />
      </Box>
    ),
  ],
};

export default meta;
type Story = StoryObj<typeof meta>;

// 폼 컨트롤 상태 스토리

// 상태 1: 초기 상태 - 빈 폼 (새 일정 추가)
export const EmptyForm: Story = {
  args: {
    editingEvent: false,
    title: '',
    setTitle: (value) => console.log('setTitle:', value),
    date: '',
    setDate: (value) => console.log('setDate:', value),
    startTime: '',
    handleStartTimeChange: (e) => console.log('startTime:', e.target.value),
    startTimeError: null,
    endTime: '',
    handleEndTimeChange: (e) => console.log('endTime:', e.target.value),
    endTimeError: null,
    description: '',
    setDescription: (value) => console.log('setDescription:', value),
    location: '',
    setLocation: (value) => console.log('setLocation:', value),
    category: '업무',
    setCategory: (value) => console.log('setCategory:', value),
    isRepeating: false,
    setIsRepeating: (value) => console.log('setIsRepeating:', value),
    repeatType: 'none',
    setRepeatType: (value) => console.log('setRepeatType:', value),
    repeatInterval: 1,
    setRepeatInterval: (value) => console.log('setRepeatInterval:', value),
    repeatEndDate: '',
    setRepeatEndDate: (value) => console.log('setRepeatEndDate:', value),
    notificationTime: 10,
    setNotificationTime: (value) => console.log('setNotificationTime:', value),
    onSubmit: () => alert('일정 추가됨'),
  },
};

// 상태 2: 폼 채워진 상태
export const FilledForm: Story = {
  args: {
    editingEvent: false,
    title: '팀 미팅',
    setTitle: (value) => console.log('setTitle:', value),
    date: '2025-10-01',
    setDate: (value) => console.log('setDate:', value),
    startTime: '10:00',
    handleStartTimeChange: (e) => console.log('startTime:', e.target.value),
    startTimeError: null,
    endTime: '11:00',
    handleEndTimeChange: (e) => console.log('endTime:', e.target.value),
    endTimeError: null,
    description: '주간 팀 미팅',
    setDescription: (value) => console.log('setDescription:', value),
    location: '회의실 A',
    setLocation: (value) => console.log('setLocation:', value),
    category: '업무',
    setCategory: (value) => console.log('setCategory:', value),
    isRepeating: false,
    setIsRepeating: (value) => console.log('setIsRepeating:', value),
    repeatType: 'none',
    setRepeatType: (value) => console.log('setRepeatType:', value),
    repeatInterval: 1,
    setRepeatInterval: (value) => console.log('setRepeatInterval:', value),
    repeatEndDate: '',
    setRepeatEndDate: (value) => console.log('setRepeatEndDate:', value),
    notificationTime: 15,
    setNotificationTime: (value) => console.log('setNotificationTime:', value),
    onSubmit: () => alert('일정 추가됨'),
  },
};

// 상태 3: 시간 유효성 검증 에러
export const TimeValidationError: Story = {
  args: {
    editingEvent: false,
    title: '회의',
    setTitle: (value) => console.log('setTitle:', value),
    date: '2025-10-01',
    setDate: (value) => console.log('setDate:', value),
    startTime: '11:00',
    handleStartTimeChange: (e) => console.log('startTime:', e.target.value),
    startTimeError: '시작 시간이 종료 시간보다 클 수 없습니다',
    endTime: '10:00',
    handleEndTimeChange: (e) => console.log('endTime:', e.target.value),
    endTimeError: '종료 시간이 시작 시간보다 작을 수 없습니다',
    description: '',
    setDescription: (value) => console.log('setDescription:', value),
    location: '',
    setLocation: (value) => console.log('setLocation:', value),
    category: '업무',
    setCategory: (value) => console.log('setCategory:', value),
    isRepeating: false,
    setIsRepeating: (value) => console.log('setIsRepeating:', value),
    repeatType: 'none',
    setRepeatType: (value) => console.log('setRepeatType:', value),
    repeatInterval: 1,
    setRepeatInterval: (value) => console.log('setRepeatInterval:', value),
    repeatEndDate: '',
    setRepeatEndDate: (value) => console.log('setRepeatEndDate:', value),
    notificationTime: 10,
    setNotificationTime: (value) => console.log('setNotificationTime:', value),
    onSubmit: () => alert('일정 추가됨'),
  },
};

// 상태 4: 반복 일정 활성화 (매일)
export const RepeatingDaily: Story = {
  args: {
    editingEvent: false,
    title: '아침 회의',
    setTitle: (value) => console.log('setTitle:', value),
    date: '2025-10-01',
    setDate: (value) => console.log('setDate:', value),
    startTime: '09:00',
    handleStartTimeChange: (e) => console.log('startTime:', e.target.value),
    startTimeError: null,
    endTime: '09:30',
    handleEndTimeChange: (e) => console.log('endTime:', e.target.value),
    endTimeError: null,
    description: '매일 진행',
    setDescription: (value) => console.log('setDescription:', value),
    location: '회의실',
    setLocation: (value) => console.log('setLocation:', value),
    category: '업무',
    setCategory: (value) => console.log('setCategory:', value),
    isRepeating: true,
    setIsRepeating: (value) => console.log('setIsRepeating:', value),
    repeatType: 'daily',
    setRepeatType: (value) => console.log('setRepeatType:', value),
    repeatInterval: 1,
    setRepeatInterval: (value) => console.log('setRepeatInterval:', value),
    repeatEndDate: '2025-10-31',
    setRepeatEndDate: (value) => console.log('setRepeatEndDate:', value),
    notificationTime: 15,
    setNotificationTime: (value) => console.log('setNotificationTime:', value),
    onSubmit: () => alert('반복 일정 추가됨'),
  },
};

// 상태 5: 반복 일정 활성화 (매주, 2주 간격)
export const RepeatingWeekly: Story = {
  args: {
    editingEvent: false,
    title: '팀 스탠드업',
    setTitle: (value) => console.log('setTitle:', value),
    date: '2025-10-02',
    setDate: (value) => console.log('setDate:', value),
    startTime: '14:00',
    handleStartTimeChange: (e) => console.log('startTime:', e.target.value),
    startTimeError: null,
    endTime: '14:30',
    handleEndTimeChange: (e) => console.log('endTime:', e.target.value),
    endTimeError: null,
    description: '2주마다 반복',
    setDescription: (value) => console.log('setDescription:', value),
    location: '온라인',
    setLocation: (value) => console.log('setLocation:', value),
    category: '업무',
    setCategory: (value) => console.log('setCategory:', value),
    isRepeating: true,
    setIsRepeating: (value) => console.log('setIsRepeating:', value),
    repeatType: 'weekly',
    setRepeatType: (value) => console.log('setRepeatType:', value),
    repeatInterval: 2,
    setRepeatInterval: (value) => console.log('setRepeatInterval:', value),
    repeatEndDate: '2025-12-31',
    setRepeatEndDate: (value) => console.log('setRepeatEndDate:', value),
    notificationTime: 30,
    setNotificationTime: (value) => console.log('setNotificationTime:', value),
    onSubmit: () => alert('반복 일정 추가됨'),
  },
};

// 상태 6: 일정 수정 모드
export const EditingMode: Story = {
  args: {
    editingEvent: true,
    title: '클라이언트 미팅',
    setTitle: (value) => console.log('setTitle:', value),
    date: '2025-10-05',
    setDate: (value) => console.log('setDate:', value),
    startTime: '15:00',
    handleStartTimeChange: (e) => console.log('startTime:', e.target.value),
    startTimeError: null,
    endTime: '16:00',
    handleEndTimeChange: (e) => console.log('endTime:', e.target.value),
    endTimeError: null,
    description: '중요한 클라이언트 미팅',
    setDescription: (value) => console.log('setDescription:', value),
    location: '카페',
    setLocation: (value) => console.log('setLocation:', value),
    category: '업무',
    setCategory: (value) => console.log('setCategory:', value),
    isRepeating: false,
    setIsRepeating: (value) => console.log('setIsRepeating:', value),
    repeatType: 'none',
    setRepeatType: (value) => console.log('setRepeatType:', value),
    repeatInterval: 1,
    setRepeatInterval: (value) => console.log('setRepeatInterval:', value),
    repeatEndDate: '',
    setRepeatEndDate: (value) => console.log('setRepeatEndDate:', value),
    notificationTime: 60,
    setNotificationTime: (value) => console.log('setNotificationTime:', value),
    onSubmit: () => alert('일정 수정됨'),
  },
};

// 상태 7: 다양한 카테고리 선택
export const PersonalCategory: Story = {
  args: {
    editingEvent: false,
    title: '개인 프로젝트',
    setTitle: (value) => console.log('setTitle:', value),
    date: '2025-10-10',
    setDate: (value) => console.log('setDate:', value),
    startTime: '18:00',
    handleStartTimeChange: (e) => console.log('startTime:', e.target.value),
    startTimeError: null,
    endTime: '20:00',
    handleEndTimeChange: (e) => console.log('endTime:', e.target.value),
    endTimeError: null,
    description: '사이드 프로젝트',
    setDescription: (value) => console.log('setDescription:', value),
    location: '집',
    setLocation: (value) => console.log('setLocation:', value),
    category: '개인',
    setCategory: (value) => console.log('setCategory:', value),
    isRepeating: false,
    setIsRepeating: (value) => console.log('setIsRepeating:', value),
    repeatType: 'none',
    setRepeatType: (value) => console.log('setRepeatType:', value),
    repeatInterval: 1,
    setRepeatInterval: (value) => console.log('setRepeatInterval:', value),
    repeatEndDate: '',
    setRepeatEndDate: (value) => console.log('setRepeatEndDate:', value),
    notificationTime: 120,
    setNotificationTime: (value) => console.log('setNotificationTime:', value),
    onSubmit: () => alert('일정 추가됨'),
  },
};

// 상태 8: 긴 설명 및 위치 텍스트
export const LongTextInput: Story = {
  args: {
    editingEvent: false,
    title: '분기별 비즈니스 리뷰 미팅',
    setTitle: (value) => console.log('setTitle:', value),
    date: '2025-10-15',
    setDate: (value) => console.log('setDate:', value),
    startTime: '09:00',
    handleStartTimeChange: (e) => console.log('startTime:', e.target.value),
    startTimeError: null,
    endTime: '12:00',
    handleEndTimeChange: (e) => console.log('endTime:', e.target.value),
    endTimeError: null,
    description: '3분기 성과 검토 및 4분기 목표 설정. 모든 팀장 필수 참석. 자료 사전 준비 필요.',
    setDescription: (value) => console.log('setDescription:', value),
    location: '컨퍼런스 홀 B (서울 강남구 테헤란로 123 빌딩 5층)',
    setLocation: (value) => console.log('setLocation:', value),
    category: '업무',
    setCategory: (value) => console.log('setCategory:', value),
    isRepeating: false,
    setIsRepeating: (value) => console.log('setIsRepeating:', value),
    repeatType: 'none',
    setRepeatType: (value) => console.log('setRepeatType:', value),
    repeatInterval: 1,
    setRepeatInterval: (value) => console.log('setRepeatInterval:', value),
    repeatEndDate: '',
    setRepeatEndDate: (value) => console.log('setRepeatEndDate:', value),
    notificationTime: 1440,
    setNotificationTime: (value) => console.log('setNotificationTime:', value),
    onSubmit: () => alert('일정 추가됨'),
  },
};
